/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Rectangle;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import loremred.Comment;
import loremred.Post;
import loremred.Usuario;
import utils.ArbolGrafico;
import utils.CustomList.Lista;
import utils.CustomList.Nodo;

/**
 *
 * @author luisf
 */
public class Home extends javax.swing.JFrame {

    private Lista<Usuario> usuarios;
    private Nodo<Usuario> siguientes;
    private Graphics g;
    private JPanel dibujo;

    private int index = 0;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    public Home(Lista<Usuario> usuarios) {
        initComponents();
        this.usuarios = usuarios;
        this.siguientes = usuarios.getRaiz();

        if (usuarios.count() >= 3) {
            index = 3;
        } else {
            index = usuarios.count();
        }
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.requestFocus();
        this.dibujo = null;
        mostrarArbol(siguientes);
        contenedorArbol.repaint();
        mostrarArbol(siguientes);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        contenedorArbol = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("LoremRed");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/profile-user.png"))); // NOI18N
        jLabel2.setText("Nombre de usuario");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/post.png"))); // NOI18N
        jLabel3.setText("News");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTextField1.setToolTipText("Dato de busqueda");

        jButton1.setText("Usuario");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton2.setText("Post");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setText("Buscar por:");

        jButton3.setText("Siguiente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Anterior");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Comentario");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        contenedorArbol.setVisible(true);

        javax.swing.GroupLayout contenedorArbolLayout = new javax.swing.GroupLayout(contenedorArbol.getContentPane());
        contenedorArbol.getContentPane().setLayout(contenedorArbolLayout);
        contenedorArbolLayout.setHorizontalGroup(
            contenedorArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenedorArbolLayout.setVerticalGroup(
            contenedorArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(contenedorArbol, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedorArbol)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedorArbol)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGap(335, 335, 335)
                .addComponent(jButton3)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int cont = 0;

        while (siguientes.getDer() != null && cont < 3) {
            siguientes = siguientes.getDer();
            cont++;
            index++;
        }

        mostrarArbol(siguientes);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int cont = 0;
        Nodo<Usuario> p = usuarios.getRaiz();
        while (p != null && cont < index - 3) {
            p = p.getDer();
            cont++;
        }

        index -= 3;
        siguientes = p.getDer();

        if (index < 1) {
            index = 1;
        }

        mostrarArbol(p);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    public void mostrarArbol(Nodo<Usuario> usuarios) {
        contenedorArbol.setTitle("arboles");
        if (dibujo != null) {
            contenedorArbol.remove(dibujo);
        } 
        dibujo = new ArbolGrafico(usuarios);
        contenedorArbol.add(dibujo);
        contenedorArbol.repaint();

    }
    /**
     * public void mostrarArbol(Nodo<Usuario> usuarios) {
     * this.contenedorArbol.removeAll();
     * contenedorArbol.setBackground(Color.WHITE); contenedorArbol.repaint();
     *
     * FontMetrics fm = g.getFontMetrics(); g.setColor(Color.red); Graphics2D
     * g2d = (Graphics2D) g;
     *
     * Rectangle dimensiones = new Rectangle(this.getSize().width / 2 - 75,
     * fm.getHeight() * 2, 150, fm.getHeight() + 5); BotonNodo padre = new
     * BotonNodo("LoremdRed", dimensiones); contenedorArbol.add(padre);
     *
     * int contUsuarios = 0; int contPosts = 0; int contComentarios = 0;
     *
     * int separacionUsuariosX = 60; int separacionpostsX = 15; int
     * separacionComentariosX = 5;
     *
     * int separacionUsuariosY = fm.getHeight() * 6; int separacionPostsY =
     * fm.getHeight() * 11; int separacionComentariosY = fm.getHeight() * 15;
     *
     * int alturaNodos = fm.getHeight() + 5; Nodo<Usuario> u = usuarios;
     *
     * while (u != null && contUsuarios < 3) { dimensiones = new
     * Rectangle(separacionUsuariosX, separacionUsuariosY, 200, fm.getHeight() +
     * 5); BotonNodo nodo = new BotonNodo(u, dimensiones);
     * g2d.drawLine(contenedorArbol.getSize().width / 2, fm.getHeight() * 3 + 5,
     * separacionUsuariosX + 100, fm.getHeight() * 6);
     * contenedorArbol.add(nodo);
     *
     * Nodo<Post> p = u.getDat().getPosts().getRaiz(); while (p != null &&
     * contPosts < 3) { dimensiones = new Rectangle(separacionpostsX,
     * fm.getHeight() * 11, 100, fm.getHeight() + 5); nodo = new BotonNodo(p,
     * dimensiones); g2d.drawLine(separacionUsuariosX + 100, separacionUsuariosY
     * + fm.getHeight(), separacionpostsX + 50, separacionPostsY);
     * nodo.setToolTipText(p.getDat().getTitle()); nodo.setVisible(true);
     * contenedorArbol.add(nodo);
     *
     * Nodo<Comment> c = p.getDat().getComments().getRaiz(); while (c != null &&
     * contComentarios < 2) { g2d.drawLine(separacionpostsX + 50, fm.getHeight()
     * * 12 + 5, separacionComentariosX + 30, fm.getHeight() * 15); dimensiones
     * = new Rectangle(separacionComentariosX, fm.getHeight() * 15, 55,
     * fm.getHeight() + 5); nodo = new BotonNodo(c, dimensiones);
     * nodo.setToolTipText("Click para ver más"); contenedorArbol.add(nodo);
     *
     * separacionComentariosX += 60; c = c.getDer(); contComentarios++; }
     *
     * if (contComentarios < 2) { separacionComentariosX += 60 * (2 -
     * contComentarios); }
     *
     * contComentarios = 0; separacionpostsX += 110; p = p.getDer();
     * contPosts++; }
     *
     * if (contPosts < 3) { separacionpostsX += 110 * (3 - contPosts); }
     *
     * separacionUsuariosX += 350; contUsuarios++; contPosts = 0; u =
     * u.getDer(); } }
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JInternalFrame contenedorArbol;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
